#!/bin/zsh

# Python aliases
alias python="python3"

# Fast fetch
alias ff="fastfetch"

# Btop
alias bt="btop"

# Nvim
alias vim="nvim"

# Directory aliases
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias ~="cd ~"

# Clear terminal
alias cls="clear"

# Git aliases
alias gs="git status"
alias ga="git add -A"
alias gc="git commit -m"
alias gp="git push"
alias gl="git log --oneline --graph --decorate"
alias lg="lazygit"

# Bat
alias cat="bat"

# Navigational aliases
alias projects="cd ~/Drives/BagEnd/Projects/"

# Pacman
alias upgrade="sudo pacman -Syu"
alias install="sudo pacman -S"
alias remove="sudo pacman -R"
alias search="pacman -Ss"
alias list="pacman -Q"
alias info="pacman -Si"

# Paru
alias pupgrade="paru -Sua"


# Docker
alias ld="lazydocker"
