#!/bin/zsh

if [ "$(uname -s)" = "Linux" ]; then
# Linux specific settings
# Nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Bun completions
[ -s "/home/alex/.bun/_bun" ] && source "/home/alex/.bun/_bun"
# Bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Deno
# Add deno completions to search path
if [[ ":$FPATH:" != *":/home/alex/.zsh/completions:"* ]]; then export FPATH="/home/alex/.zsh/completions:$FPATH"; fi
. "/home/alex/.deno/env"
fi

if [ "$(uname -s)" = "Darwin" ]; then
# MacOS specific settings
# Nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Bun completions
[ -s "/Users/alex/.bun/_bun" ] && source "/Users/alex/.bun/_bun"
# Bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Deno
# Add deno completions to search path
if [[ ":$FPATH:" != *":/Users/alex/.zsh/completions:"* ]]; then export FPATH="/Users/alex/.zsh/completions:$FPATH"; fi
. "/Users/alex/.deno/env"
fi

# pnpm
export PNPM_HOME="/home/alex/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

