#!/bin/zsh

# Setting up aliases
source ~/dotfiles/zsh/zsh-configs/zsh-aliases

# Runtimes and specific package needs
source ~/dotfiles/zsh/zsh-configs/zsh-package-utils

# Starship prompt
source ~/dotfiles/zsh/zsh-configs/zsh-evals

# Zsh plugins
source ~/dotfiles/zsh/zsh-configs/zsh-plugins

