-- Customize Treesitter
---@type LazySpec
return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "angular",
      "bash",
      "c_sharp",
      "cmake",
      "cpp",
      "css",
      "dockerfile",
      "fish",
      "go",
      "gomod",
      "html",
      "http",
      "java",
      "javadoc",
      "javascript",
      "json",
      "lua",
      "make",
      "markdown",
      "mermaid",
      "php",
      "prisma",
      "python",
      "regex",
      "rust",
      "scss",
      "sql",
      "tmux",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
      "zig",
      -- add more arguments for adding more treesitter parsers
    },
  },
}
